/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "./rrc-15.6.0.asn1"
 * 	`asn1c -fcompound-names -gen-PER -no-gen-example`
 */

#ifndef	_SIB1_vExt_IEs_H_
#define	_SIB1_vExt_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SIB1-vExt-IEs */
typedef struct SIB1_vExt_IEs {
	OCTET_STRING_t	 timestampBE;
	OCTET_STRING_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SIB1_vExt_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SIB1_vExt_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SIB1_vExt_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_SIB1_vExt_IEs_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SIB1_vExt_IEs_H_ */
#include <asn_internal.h>
